export enum RollerItemMode {
    SHORT = "short",
    LONG = "long",
}

export enum RollerItemCharSet {
    NUMBER = "number",
    ALPHABET = "alphabet",
}

export const RollerCharSet = {
    [RollerItemCharSet.NUMBER]: [" ", ...[...Array(10).keys()].map(String), ","],
    [RollerItemCharSet.ALPHABET]: [
        " ",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "-",
    ],
};
